spring.application.name=pact-backend
# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/pact_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Bhavya@2005

server.port=8081

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret (Keep this safe!)
jwt.secret=your-very-long-and-secure-random-string-here-to-keep-things-safe

